apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-service
  replicas: 2
  selector:
    matchLabels:
      app: rating-service
  template:
    metadata:
      labels:
        app: rating-service
    spec:
      containers:
        - name: rating-service
          image: rating-service/rating-service:v1
          ports:
            - containerPort: 8080

          env:
            - name: FEATURE_FLAG
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: FEATURE_FLAG
            - name: API_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: API_ENDPOINT

            - name: SENSITIVE_ENV
              valueFrom:
               secretKeyRef:
                 name: my-secret
                 key: sensitive-key