apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-service
  labels:
    app: rating-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rating-service
  template:
    metadata:
      labels:
        app: rating-service
    spec:
      containers:
        - name: rating-service
          image: lucperrom1/rating-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: FEATURE_FLAG
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: FEATURE_FLAG
            - name: API_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: API_ENDPOINT
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret 
                  key: MONGODB_USER 
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret  
                  key: MONGODB_PASSWORD 
